---
title: "HW1_UI reduced-Simulation"
output: html_document
---

## 1.
```{r}
library(sandwich)
data = read.csv('UI_HW_1.csv')
attach(data)

# (1)
lm1 = lm(iqr_gip ~ recession)
summary(lm1)$coef[2,1]
# (1-1)
summary(lm1)$coef[2,2]
# (1-2)
HC.se = sqrt(vcovHC(lm1)[2,2]); HC.se
# (1-3)
HAC.se = sqrt(vcovHAC(lm1)[2,2]); HAC.se

# (2-1)
var.test(iqr_gip[recession==1],iqr_gip[recession==0])
# HO 기각. 이분산

# (2-2)
# variance
var_U = var(iqr_gip[recession==0])
var_D = var(iqr_gip[recession==1])

# 등분산 변환
Y_str = ifelse(recession==0, iqr_gip/sqrt(var_U), iqr_gip/sqrt(var_D))
X_str = ifelse(recession==0, recession/sqrt(var_U), recession/sqrt(var_D))
I_str = ifelse(recession==0, 1/sqrt(var_U), 1/sqrt(var_D))
# regression fitting
lm2 = lm(Y_str ~ X_str + I_str -1)
summary(lm2)$coef[1,1]
summary(lm2)$coef[1,2]

detach(data)
```



## 2. 
```{r}
# (1)
set.seed(1)

# (2)
n.data = 2000
alpha = 1
beta = 0

x = rnorm(n.data,0,1)
a = rnorm(n.data,0,1)
u = x^alpha * a
y = x*beta + u 

ols.fit = lm(y ~ x)
ols.beta = summary(ols.fit)$coef[2,1]; ols.beta
ols.se = summary(ols.fit)$coef[2,2]; ols.se
hc.se = sqrt(vcovHC(ols.fit)[2,2]); hc.se


# (3)
set.seed(1)
n.sim = 1000

alpha = 1
beta = 0

ols.beta = c(); ols.se = c(); hc.se = c()

for (i in 1:n.sim){
  
  x = rnorm(n.data,0,1)
  a = rnorm(n.data,0,1)
  u = x^alpha * a
  y = x*beta + u 
  
  ols.fit = lm(y ~ x)
  ols.beta[i] = summary(ols.fit)$coef[2,1]
  ols.se[i] = summary(ols.fit)$coef[2,2]
  hc.se[i] = sqrt(vcovHC(ols.fit)[2,2])
}

mean(ols.beta)            # mean of olse
sd(ols.beta)              # se of olse
mean(ols.se)              # mean of ols se
mean(hc.se)               # HC.se


#(4)
set.seed(1)
gls.beta = c(); gls.se = c()

for (i in 1:n.sim){
  
  x = rnorm(n.data,0,1)
  var_u = abs(x)
  a = rnorm(n.data,0,1)
  u = x^alpha * a
  y = x*beta + u 
   
  
  # 등분산 변환
  x_str = x / sqrt(var_u)
  y_str = y / sqrt(var_u)
  I_str = 1 / sqrt(var_u)
  
  
  gls.fit = lm(y_str ~ x_str +  I_str - 1)
  
  gls.beta[i] = summary(gls.fit)$coef[1,1]
  gls.se[i] = summary(gls.fit)$coef[1,2]
}

mean(gls.beta)
sd(gls.beta)


```

