---
title: "hw2_자기상관회귀시뮬레이션_Volatility Spillover Index 데이터 분석"
output: html_document
---


```{r}
library(sandwich)

set.seed(1)
n=100; phi_x=0.5; phi_u=0.7; n_sim=10000
b_=c(); b.gls_=c()
ols.se_=c(); hac.se_=c(); gls.se_=c(); 
I1_=c(); I2_=c(); I3_=c()

for (i in 1:n_sim) {
  x=c(); y=c(); u=c(); 
  x[1]=0; u[1]=0;
  e=rnorm(n); a=rnorm(n); u=rnorm(n);
  y[1]=1+x[1]+u[1]
  
  for (t in 2:n) {
    x[t]=phi_x*x[t-1]+e[t]
    u[t]=phi_u*u[t-1]+a[t]
    y[t]=1+x[t]+u[t] }
  
  ols.fit=lm(y~x)
  b=ols.fit$coef[2]
  ols.se = summary(ols.fit)$coef[2,2] 
  hac.se = sqrt(vcovHAC(ols.fit)[2,2])
  ols.res.0=ols.fit$residual[2:n] 
  ols.res.1=ols.fit$residual[1:(n-1)]
  phi_u.hat=lm(ols.res.0~ols.res.1 -1)$coef[1]
  
  x_s = c(); y_s = c()
  for (t in 2:n) {
    x_s[t]=x[t]-phi_u.hat*x[t-1]
    y_s[t]=y[t]-phi_u.hat*y[t-1] }
  
  gls.fit = lm(y_s ~ x_s)
  b.gls = gls.fit$coef[2]
  gls.se=summary(gls.fit)$coef[2,2] 
  
  t1=(b-1)/ols.se
  t2=(b-1)/hac.se
  t3=(b.gls-1)/gls.se
  
  I1=ifelse(abs(t1)>1.96,1,0)
  I2=ifelse(abs(t2)>1.96,1,0)
  I3=ifelse(abs(t3)>1.96,1,0)
  
  b_[i]=b
  ols.se_[i]=ols.se
  hac.se_[i]=hac.se
  b.gls_[i]=b.gls
  gls.se_[i]=gls.se
  I1_[i]=I1; I2_[i]=I2; I3_[i]=I3
}

mean(b_); sd(b_); 
mean(b.gls_); sd(b.gls_)
mean(ols.se_); mean(hac.se_); mean(gls.se_)
mean(I1_); mean(I2_); mean(I3_)
```

```{r}
data = read.csv('VSI.csv')
library(lmtest)
attach(data)
colnames(data)
ols = lm(index~crisis)
acf(ols$residual)
dwtest(ols)

b = summary(ols)$coef[2,1]; b
ols.se = summary(ols)$coef[2,2]; ols.se
hac.se = sqrt(vcovHAC(ols)[2,2]); hac.se


e = ols$residuals
ols2 <- lm(e[2:length(e)]~e[1:(length(e)-1)]-1)

psi.hat = coef(ols2)
y0 = index[2:length(index)]
y1 = index[1:length(index)-1]
x0 = crisis[2:length(crisis)]
x1 = crisis[1:length(crisis)-1]

y.str = y0 - psi.hat*y1
x.str = x0 - psi.hat*x1

fgls = lm(y.str~x.str)
fgls.b = summary(fgls)$coef[2,1]; fgls.b
fgls.se = summary(fgls)$coef[2,2]; fgls.se
c(fgls.b-1.96*fgls.se, fgls.b+1.96*fgls.se)

u = ols$residuals
plot(u, type='l')

library(fGarch)
garch.fit = garchFit(~garch(1,1), data = u, trace = F, include.mean = F)
garch.fit
```

