---
title: "경제자료분석 기말 프로젝트 코드"
author: '212STG10 박영은'
output: html_document
---


A.

(0)
```{r}
library(lubridate)

data1 <- read.csv('income.csv')
data1$date = make_datetime(data1$year,data1$month)
data1 <- data1[3:4]
names(data1) <- c('income', 'date')

data2 <- read.csv('nike.csv')[c(1,2,3,7)]
data2$date = make_datetime(data2$year,data2$month)
data2 <- data2[3:5]
names(data2) <- c('price', 'demands', 'date')

data <- merge(data1, data2, by='date')

test <- data[(nrow(data)-4):nrow(data), ]
train <- data[1:(nrow(data)-5),]
```


(1)
```{r}
data_2 <- data
data_2[(nrow(data_2)-4):nrow(data_2), c('demands')] = NA

attach(data_2)

log.demands <- log(demands)
a<- seq(1, 250, 15)

plot(log.demands, type='l', xaxt="n", xlab='date')
axis(side=1,at=a,labels=date[a])
```

(2)

```{r}
log.price <- log(price)
a<- seq(1, 250, 15)
plot(log.price, type='l', xaxt="n", xlab='date')
axis(side=1,at=a,labels=date[a])

detach(data_2)
```

(3)
```{r}
attach(train)

log.price <- log(price)
log.demands <- log(demands)

lm1 <- lm(log.demands~log.price)
summary(lm1)$coef[2,1]

plot(log.price, log.demands, asp=1)
cor(log.price, log.demands)
```


(4)
```{r}
detach(train)
attach(data_2)
log.income <- log(income)

a<- seq(1, 250, 15)
plot(log.income, type='l', xaxt="n", xlab='date')
axis(side=1,at=a,labels=date[a])

detach(data_2)
attach(train)

library(AER)

log.price <- log(price)
log.demands <- log(demands)
log.income <- log(income)

lm2 <- lm(log.demands ~log.price + log.income)
summary(lm2)$coef[2,1]
summary(lm1)$coef[2,1]
```


(5)
```{r}
e.sq = lm2$residuals^2

lm3 <- lm(e.sq ~ I(log.income^2) + I(log.demands^2) +(log.income+log.demands)^2)

nr2 = summary(lm3)$r.square * nrow(data)

chisqq = qchisq(p=0.05, df=5, lower.tail = F)
chisqq
nr2
nr2 > chisqq   #이분산성 존재o
```


(6)
```{r}
library(lmtest)

acf(lm2$residual)
dwtest(lm2)   # 자기상관성 존재o
```


(7)
```{r}
n=length(log.demands)
t = seq(1,n)

F.break = c()
for (tau in (0.15*n):(0.85*n)){
  D = ifelse(t<=tau, 0, 1)
  OLS.break = lm(log.demands~1+log.income+log.price+D+D:log.price)
  F.break[tau] = anova(lm2, OLS.break)$F[2]
}
plot(F.break, type = 'l', xaxt="n", xlab='date')
axis(side=1,at=a,labels=date[a])
abline(v=which.max(F.break), col='blue')

max(F.break, na.rm=TRUE)   # 0.05를 기준으로 H0 기각, 브레이크 존재
which.max(F.break)
date[43]   # 브레이크 2015년 7월

D = ifelse(t<=43, 0, 1)
OLS.break = lm(log.demands~1+log.income+log.price+D+D:log.price)
anova(lm2, OLS.break)
```


(8)
```{r}
b = summary(lm2)$coef[2,1]; b
ols.se = summary(lm2)$coef[2,2]; ols.se
hc.se = sqrt(vcovHC(lm2)[2,2]); hc.se
hac.se = sqrt(vcovHAC(lm2)[2,2]); hac.se
```


(9)

HAC 표준오차가 가장 적절하다. 오차항은 이분산성과 자기상관성을 가진다는 것이 각각 (5), (6)번에서 검증되었다. HAC 표준오차는 오차항의 자기상관과 이분산성을 감안하여 계산되었기 때문에 둘 다 모두 존재하는 해당 경우에 가장 타당한 표준오차이다.


(10)
```{r}
c(b-1.96*hac.se, b+1.96*hac.se)
```

B.

(1)
```{r}
acf(log.demands)

d.log.demands = log.demands[2:length(log.demands)]- log.demands[1:length(log.demands)-1]

library(forecast)
bic=matrix(rep(0, 10*10), 10, 10);
for (p in 1:10) {for (q in 1:10) {
 bic[p,q] = Arima(log.demands, order=c(p-1,1,q-1))$bic}}

min(bic)  # p=3, q=4
bic

arima.fit = Arima(log.demands, order=c(2,1,3))
arima.hat = forecast(arima.fit, h=5)
arima.hat

a<- seq(1, 250, 15)
plot(arima.hat, xaxt="n", xlab='date')
axis(side=1,at=a,labels=data_2$date[a])
```


(2)
```{r}
#### 단위근검정
aic1 = c()
for(p in 1:10){
  ar.fit1 = Arima(log.demands, order = c(p,0,0))
  aic1[p] = ar.fit1$aic
}
plot(aic1)
which.min(aic1)

plot(log.demands, type = 'l')
library(fUnitRoots)
adfTest(log.demands, type = 'c', lags = 8)   # 단위근 존재 계열


aic2 = c()
for(p in 1:20){
  ar.fit2 = Arima(log.price, order = c(p,0,0), method="ML")
  aic2[p] = ar.fit2$aic
}

plot(aic2)
which.min(aic2)

plot(log.price)
adfTest(log.price, type = 'ct', lags = 0)   # 단위근 계열


aic3 = c()
for(p in 1:10){
  ar.fit3 = Arima(log.income, order = c(p,0,0), method="ML")
  aic3[p] = ar.fit3$aic
}
plot(aic3)
which.min(aic3)

plot(log.income)
adfTest(log.income, type = 'ct', lags = 9)   # 단위근 계열
```


```{r}
##### 모델링
bic=c();
for (p in 1:10) {
 bic[p] = Arima(log.demands, order=c(p,1,0))$bic}
which.min(bic)  # p=5

# ADL(5,5,5)
log.Y = log(data_2$demands)
log.X = log(data_2$price)
log.Z = log(data_2$income)


log.Y0 = log.Y[7:nrow(data_2)]
log.Y1 = log.Y[6:(nrow(data_2)-1)]
log.Y2 = log.Y[5:(nrow(data_2)-2)]
log.Y3 = log.Y[4:(nrow(data_2)-3)]
log.Y4 = log.Y[3:(nrow(data_2)-4)]
log.Y5 = log.Y[2:(nrow(data_2)-5)]
log.Y6 = log.Y[1:(nrow(data_2)-6)]

dlog.Y_0 = log.Y0 - log.Y1
dlog.Y_1 = log.Y1 - log.Y2
dlog.Y_2 = log.Y2 - log.Y3
dlog.Y_3 = log.Y3 - log.Y4
dlog.Y_4 = log.Y4 - log.Y5
dlog.Y_5 = log.Y5 - log.Y6

log.X0 = log.X[7:nrow(data_2)]
log.X1 = log.X[6:(nrow(data_2)-1)]
log.X2 = log.X[5:(nrow(data_2)-2)]
log.X3 = log.X[4:(nrow(data_2)-3)]
log.X4 = log.X[3:(nrow(data_2)-4)]
log.X5 = log.X[2:(nrow(data_2)-5)]
log.X6 = log.X[1:(nrow(data_2)-6)]

dlog.X_0 = log.X0 - log.X1
dlog.X_1 = log.X1 - log.X2
dlog.X_2 = log.X2 - log.X3
dlog.X_3 = log.X3 - log.X4
dlog.X_4 = log.X4 - log.X5
dlog.X_5 = log.X5 - log.X6

log.Z0 = log.Z[7:nrow(data_2)]
log.Z1 = log.Z[6:(nrow(data_2)-1)]
log.Z2 = log.Z[5:(nrow(data_2)-2)]
log.Z3 = log.Z[4:(nrow(data_2)-3)]
log.Z4 = log.Z[3:(nrow(data_2)-4)]
log.Z5 = log.Z[2:(nrow(data_2)-5)]
log.Z6 = log.Z[1:(nrow(data_2)-6)]

dlog.Z_0 = log.Z0 - log.Z1
dlog.Z_1 = log.Z1 - log.Z2
dlog.Z_2 = log.Z2 - log.Z3
dlog.Z_3 = log.Z3 - log.Z4
dlog.Z_4 = log.Z4 - log.Z5
dlog.Z_5 = log.Z5 - log.Z6

N = length(dlog.Y_0)-5

adl = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] +  dlog.Y_3[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_1[1:N] + dlog.X_2[1:N] + dlog.X_3[1:N] + dlog.X_4[1:N] +dlog.X_5[1:N] + dlog.Z_1[1:N] + dlog.Z_2[1:N] + dlog.Z_3[1:N] + dlog.Z_4[1:N] + dlog.Z_5[1:N])

summary(adl)
```


```{r}
# prediction
y.hat = c()
lower = c()
upper = c()
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N], dlog.Y_2 = dlog.Y_1[N],
                      dlog.Y_3= dlog.Y_2[N], dlog.Y_4 = dlog.Y_3[N],
                      dlog.Y_5= dlog.Y_4[N],
                      dlog.X_1=dlog.X_0[N], dlog.X_2= dlog.X_1[N], 
                      dlog.X_3=dlog.X_2[N], dlog.X_4= dlog.X_3[N], 
                      dlog.X_5=dlog.X_4[N],
                      dlog.Z_1 = dlog.Z_0[N], dlog.Z_2 = dlog.Z_1[N],
                      dlog.Z_3 = dlog.Z_2[N], dlog.Z_4 = dlog.Z_3[N],
                      dlog.Z_5 = dlog.Z_4[N])

pred <- predict(adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat[1] <- pred[1] + log.Y0[N]
lower[1] <- pred[2] + log.Y0[N]
upper[1] <- pred[3] + log.Y0[N]

dlog.Y_0[N+1] = pred[1]
log.Y0[N+1] = y.hat[1]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+1], dlog.Y_2 = dlog.Y_1[N+1],
                      dlog.Y_3= dlog.Y_2[N+1], dlog.Y_4 = dlog.Y_3[N+1],
                      dlog.Y_5= dlog.Y_4[N+1],
                      dlog.X_1= dlog.X_0[N+1], dlog.X_2= dlog.X_1[N+1], 
                      dlog.X_3= dlog.X_2[N+1], dlog.X_4= dlog.X_3[N+1], 
                      dlog.X_5= dlog.X_4[N+1],
                      dlog.Z_1 = dlog.Z_0[N+1], dlog.Z_2 = dlog.Z_1[N+1],
                      dlog.Z_3 = dlog.Z_2[N+1], dlog.Z_4 = dlog.Z_3[N+1],
                      dlog.Z_5 = dlog.Z_4[N+1])
pred <- predict(adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat[2] <- pred[1] + log.Y0[N+1]
lower[2] <- pred[2] + log.Y0[N+1]
upper[2] <- pred[3] + log.Y0[N+1]


dlog.Y_0[N+2] = pred[1]
dlog.Y_1[N+2] = dlog.Y_0[N+1]
log.Y0[N+2] = y.hat[2]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+2], dlog.Y_2 = dlog.Y_1[N+2],
                      dlog.Y_3= dlog.Y_2[N+2], dlog.Y_4 = dlog.Y_3[N+2],
                      dlog.Y_5= dlog.Y_4[N+2],
                      dlog.X_1= dlog.X_0[N+2], dlog.X_2= dlog.X_1[N+2], 
                      dlog.X_3= dlog.X_2[N+2], dlog.X_4= dlog.X_3[N+2], 
                      dlog.X_5= dlog.X_4[N+2],
                      dlog.Z_1 = dlog.Z_0[N+2], dlog.Z_2 = dlog.Z_1[N+2],
                      dlog.Z_3 = dlog.Z_2[N+2], dlog.Z_4 = dlog.Z_3[N+2],
                      dlog.Z_5 = dlog.Z_4[N+2])
pred <- predict(adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat[3] <- pred[1] + log.Y0[N+2]
lower[3] <- pred[2] + log.Y0[N+2]
upper[3] <- pred[3] + log.Y0[N+2]

dlog.Y_0[N+3] = pred[1]
dlog.Y_1[N+3] = dlog.Y_0[N+2]
dlog.Y_2[N+3] = dlog.Y_1[N+2]
log.Y0[N+3] = y.hat[3]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+3], dlog.Y_2 = dlog.Y_1[N+3],
                      dlog.Y_3= dlog.Y_2[N+3], dlog.Y_4 = dlog.Y_3[N+3],
                      dlog.Y_5= dlog.Y_4[N+3],
                      dlog.X_1=dlog.X_0[N+3], dlog.X_2= dlog.X_1[N+3], 
                      dlog.X_3=dlog.X_2[N+3], dlog.X_4= dlog.X_3[N+3], 
                      dlog.X_5=dlog.X_4[N+3],
                      dlog.Z_1 = dlog.Z_0[N+3], dlog.Z_2 = dlog.Z_1[N+3],
                      dlog.Z_3 = dlog.Z_2[N+3], dlog.Z_4 = dlog.Z_3[N+3],
                      dlog.Z_5 = dlog.Z_4[N+3])
pred <- predict(adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat[4] <- pred[1] + log.Y0[N+3]
lower[4] <- pred[2] + log.Y0[N+3]
upper[4] <- pred[3] + log.Y0[N+3]

dlog.Y_0[N+4] = pred[1]
dlog.Y_1[N+4] = dlog.Y_0[N+3]
dlog.Y_2[N+4] = dlog.Y_1[N+3]
dlog.Y_3[N+4] = dlog.Y_2[N+3]
log.Y0[N+4] = y.hat[4]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+4], dlog.Y_2 = dlog.Y_1[N+4],
                      dlog.Y_3= dlog.Y_2[N+4], dlog.Y_4 = dlog.Y_3[N+4],
                      dlog.Y_5= dlog.Y_4[N+4],
                      dlog.X_1=dlog.X_0[N+4], dlog.X_2= dlog.X_1[N+4], 
                      dlog.X_3=dlog.X_2[N+4], dlog.X_4= dlog.X_3[N+4], 
                      dlog.X_5=dlog.X_4[N+4],
                      dlog.Z_1 = dlog.Z_0[N+4], dlog.Z_2 = dlog.Z_1[N+4],
                      dlog.Z_3 = dlog.Z_2[N+4], dlog.Z_4 = dlog.Z_3[N+4],
                      dlog.Z_5 = dlog.Z_4[N+4])
pred <- predict(adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat[5] <- pred[1] + log.Y0[N+4]
lower[5] <- pred[2] + log.Y0[N+4]
upper[5] <- pred[3] + log.Y0[N+4]

y.hat
```


```{r}
### plot
plot(log.demands[1:nrow(train)], type="l", xlim = c(0,125), ylim = c(4.2,6), xaxt="n", xlab='date', ylab = 'log.demands')
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), y.hat, col="blue", lwd=2)
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), upper, col="red", lwd=1, lty=2)
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), lower, col="red", lwd=1)
polygon(c(nrow(train)+1, nrow(train)+1, nrow(train)+2, nrow(train)+3,nrow(train)+4, nrow(train)+5, nrow(train)+5), c(0,upper[1], upper[2], upper[3], upper[4], upper[5], 0), col=adjustcolor("red", alpha=0.1), border=NA)
polygon(c(nrow(train)+1, nrow(train)+1, nrow(train)+2, nrow(train)+3,nrow(train)+4, nrow(train)+5, nrow(train)+5), c(4.13,lower[1], lower[2], lower[3], lower[4], lower[5], 4.13), col=adjustcolor("white", alpha=1), border=NA)

a<- seq(1, 250, 15)
axis(side=1,at=a,labels=data_2$date[a])
```


```{r}
# reduced model
library(MASS)
full.model.adl <- adl
step.model.adl <- stepAIC(full.model.adl, direction='both', trace=F)
summary(step.model.adl)
reduced.adl <- lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] + 
    dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_1[1:N] + dlog.X_2[1:N] + 
    dlog.X_3[1:N] + dlog.X_4[1:N] + dlog.Z_3[1:N])
```


```{r}
# prediction for reduced model
y.hat2 = c()
lower2 = c()
upper2 = c()
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N], dlog.Y_2 = dlog.Y_1[N],
                     dlog.Y_4 = dlog.Y_3[N], dlog.Y_5= dlog.Y_4[N],
                      dlog.X_1=dlog.X_0[N], dlog.X_2= dlog.X_1[N], 
                      dlog.X_3=dlog.X_2[N], dlog.X_4= dlog.X_3[N],
                      dlog.Z_3 = dlog.Z_2[N])

pred <- predict(reduced.adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat2[1] <- pred[1] + log.Y0[N]
lower2[1] <- pred[2] + log.Y0[N]
upper2[1] <- pred[3] + log.Y0[N]

dlog.Y_0[N+1] = pred[1]
log.Y0[N+1] = y.hat2[1]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+1], dlog.Y_2 = dlog.Y_1[N+1],
                      dlog.Y_4 = dlog.Y_3[N+1], dlog.Y_5= dlog.Y_4[N+1],
                      dlog.X_1= dlog.X_0[N+1], dlog.X_2= dlog.X_1[N+1], 
                      dlog.X_3= dlog.X_2[N+1], dlog.X_4= dlog.X_3[N+1], 
                      dlog.Z_3 = dlog.Z_2[N+1])
pred <- predict(reduced.adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat2[2] <- pred[1] + log.Y0[N+1]
lower2[2] <- pred[2] + log.Y0[N+1]
upper2[2] <- pred[3] + log.Y0[N+1]


dlog.Y_0[N+2] = pred[1]
dlog.Y_1[N+2] = dlog.Y_0[N+1]
log.Y0[N+2] = y.hat2[2]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+2], dlog.Y_2 = dlog.Y_1[N+2],
                      dlog.Y_4 = dlog.Y_3[N+2], dlog.Y_5= dlog.Y_4[N+2],
                      dlog.X_1= dlog.X_0[N+2], dlog.X_2= dlog.X_1[N+2], 
                      dlog.X_3= dlog.X_2[N+2], dlog.X_4= dlog.X_3[N+2],
                      dlog.Z_3 = dlog.Z_2[N+2])
pred <- predict(reduced.adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat2[3] <- pred[1] + log.Y0[N+2]
lower2[3] <- pred[2] + log.Y0[N+2]
upper2[3] <- pred[3] + log.Y0[N+2]

dlog.Y_0[N+3] = pred[1]
dlog.Y_1[N+3] = dlog.Y_0[N+2]
dlog.Y_2[N+3] = dlog.Y_1[N+2]
log.Y0[N+3] = y.hat2[3]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+3], dlog.Y_2 = dlog.Y_1[N+3],
                      dlog.Y_4 = dlog.Y_3[N+3], dlog.Y_5= dlog.Y_4[N+3],
                      dlog.X_1=dlog.X_0[N+3], dlog.X_2= dlog.X_1[N+3], 
                      dlog.X_3=dlog.X_2[N+3], dlog.X_4= dlog.X_3[N+3],
                      dlog.Z_3 = dlog.Z_2[N+3])
pred <- predict(reduced.adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat2[4] <- pred[1] + log.Y0[N+3]
lower2[4] <- pred[2] + log.Y0[N+3]
upper2[4] <- pred[3] + log.Y0[N+3]

dlog.Y_0[N+4] = pred[1]
dlog.Y_1[N+4] = dlog.Y_0[N+3]
dlog.Y_2[N+4] = dlog.Y_1[N+3]
dlog.Y_3[N+4] = dlog.Y_2[N+3]
log.Y0[N+4] = y.hat2[4]
new.dat <- data.frame(dlog.Y_1= dlog.Y_0[N+4], dlog.Y_2 = dlog.Y_1[N+4],
                      dlog.Y_4 = dlog.Y_3[N+4], dlog.Y_5= dlog.Y_4[N+4],
                      dlog.X_1=dlog.X_0[N+4], dlog.X_2= dlog.X_1[N+4], 
                      dlog.X_3=dlog.X_2[N+4], dlog.X_4= dlog.X_3[N+4],
                      dlog.Z_3 = dlog.Z_2[N+4])
pred <- predict(reduced.adl, newdata = new.dat, interval = 'prediction')[1,]
y.hat2[5] <- pred[1] + log.Y0[N+4]
lower2[5] <- pred[2] + log.Y0[N+4]
upper2[5] <- pred[3] + log.Y0[N+4]


y.hat2
```


```{r}
### plot
plot(log.demands[1:nrow(train)], type="l", xlim = c(0,125), ylim = c(4.2,6), xaxt="n", xlab='date', ylab = 'log.demands')
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), y.hat2, col="blue", lwd=2)
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), upper2, col="red", lwd=1, lty=2)
lines(c(nrow(train)+1, nrow(train)+2, nrow(train)+3, nrow(train)+4, nrow(train)+5), lower2, col="red", lwd=1)
polygon(c(nrow(train)+1, nrow(train)+1, nrow(train)+2, nrow(train)+3,nrow(train)+4, nrow(train)+5, nrow(train)+5), c(0,upper[1], upper[2], upper[3], upper[4], upper[5], 0), col=adjustcolor("red", alpha=0.1), border=NA)
polygon(c(nrow(train)+1, nrow(train)+1, nrow(train)+2, nrow(train)+3,nrow(train)+4, nrow(train)+5, nrow(train)+5), c(4.13,lower[1], lower[2], lower[3], lower[4], lower[5], 4.13), col=adjustcolor("white", alpha=1), border=NA)

a<- seq(1, 250, 15)
axis(side=1,at=a,labels=data_2$date[a])
```


(3)
```{r}
full1 = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] +  dlog.Y_3[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_1[1:N] + dlog.X_2[1:N] + dlog.X_3[1:N] + dlog.X_4[1:N] +dlog.X_5[1:N] + dlog.Z_1[1:N] + dlog.Z_2[1:N] + dlog.Z_3[1:N] + dlog.Z_4[1:N] + dlog.Z_5[1:N])

reduced1 = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] +  dlog.Y_3[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.Z_1[1:N] + dlog.Z_2[1:N] + dlog.Z_3[1:N] + dlog.Z_4[1:N] + dlog.Z_5[1:N])

anova(reduced1,full1)  #Granger cause한다

full2 = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_1[1:N] + dlog.X_2[1:N] + dlog.X_3[1:N] + dlog.X_4[1:N] +dlog.Z_3[1:N] )

reduced2 = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.Z_3[1:N])

anova(reduced2,full2)  #Granger cause한다
```


(4)
```{r}
aic1 = c()
for(p in 1:10){
  ar.fit1 = Arima(log.demands, order = c(p,0,0))
  aic1[p] = ar.fit1$aic
}
plot(aic1)
which.min(aic1)

plot(log.demands, type = 'l')

library(fUnitRoots)
adfTest(log.demands, type = 'c', lags = 8)   # 단위근 존재 계열


aic2 = c()
for(p in 1:20){
  ar.fit2 = Arima(log.price, order = c(p,0,0), method="ML")
  aic2[p] = ar.fit2$aic
}

plot(aic2)
which.min(aic2)

plot(log.price)
adfTest(log.price, type = 'ct', lags = 0)   # 단위근 계열


aic3 = c()
for(p in 1:10){
  ar.fit3 = Arima(log.income, order = c(p,0,0), method="ML")
  aic3[p] = ar.fit3$aic
}
plot(aic3)
which.min(aic3)

plot(log.income)
adfTest(log.income, type = 'ct', lags = 9)   # 단위근 계열
```


(5)
```{r}
library(urca)
dataf = data.frame(y1 = log.demands, y2 = log.price, y3 = log.income)
rank.result = ca.jo(dataf, type = 'eigen', ecdet = 'const')
summary(rank.result) 
```


C.

(1)
```{r}
############### ARIMA 모형
m = 0.15 * N
e.arima = c()
for (k in 1:m) {n = N-k; arima.fit = Arima(log.demands, order=c(2,1,3)); arima.hat = forecast(arima.fit, h=1)$mean[1]; e.arima[k] = log.demands[n+1] - arima.hat}
sd(e.arima)
```


(2)
```{r}
############### ADL 모형
e.adl.1 = c()
for (k in 1:m) {
  n = N-k; 
  adl.fit = lm(dlog.Y_0[1:n] ~ dlog.Y_1[1:n] + dlog.Y_2[1:n] +  dlog.Y_3[1:n] + dlog.Y_4[1:n] + dlog.Y_5[1:n] + dlog.X_1[1:n] + dlog.X_2[1:n] + dlog.X_3[1:n] + dlog.X_4[1:n] +dlog.X_5[1:n] + dlog.Z_1[1:n] + dlog.Z_2[1:n] + dlog.Z_3[1:n] + dlog.Z_4[1:n] + dlog.Z_5[1:n]); 
  beta = adl.fit$coef; 
  adl.d.hat = beta[1] + beta[2]*dlog.Y_0[n] + beta[3]*dlog.Y_1[n] + beta[4]*dlog.Y_2[n] + beta[5]*dlog.Y_3[n] + beta[6]*dlog.Y_4[n] + beta[7]*dlog.X_0[n] + beta[8]*dlog.X_1[n] + beta[9]*dlog.X_2[n] + beta[10]*dlog.X_3[n] + beta[11]*dlog.X_4[n] + beta[12]*dlog.Z_0[n] + beta[13]*dlog.Z_1[n] + beta[14]*dlog.Z_2[n] + beta[15]*dlog.Z_3[n] + beta[16]*dlog.Z_4[n]; 
  adl.hat = log.Y[n] + adl.d.hat; 
  e.adl.1[k] = log.Y[n+1] - adl.hat}

sd(e.adl.1)
```


```{r}
############### ADL 모형 reduced model
e.adl.1.reduced = c()
for (k in 1:m) {
  n = N-k; 
  adl.fit = lm(dlog.Y_0[1:n] ~ dlog.Y_1[1:n] + dlog.Y_2[1:n] + dlog.Y_4[1:n] + dlog.Y_5[1:n] + dlog.X_1[1:n] + dlog.X_2[1:n] + dlog.X_3[1:n] + dlog.X_4[1:n] + dlog.Z_3[1:n]);
  beta = adl.fit$coef; 
  adl.d.hat = beta[1] + beta[2]*dlog.Y_0[n] + beta[3]*dlog.Y_1[n] + beta[4]*dlog.Y_3[n] + beta[5]*dlog.Y_4[n] + beta[6]*dlog.X_0[n] + beta[7]*dlog.X_1[n] + beta[8]*dlog.X_2[n] + beta[9]*dlog.X_3[n] + beta[10]*dlog.Z_2[n] ; 
  adl.hat = log.Y[n] + adl.d.hat;
  e.adl.1.reduced[k] = log.Y[n+1] - adl.hat}

sd(e.adl.1.reduced)
```


(3)
```{r}
############### ADL_EC 모형
e.adl.2 = c()
for (k in 1:m) {
  n = N-k; 
  z = lm(log.Y0[1:n]~log.X0[1:n]+log.Z0[1:n])$residual;
  adl.fit2 = lm(dlog.Y_0[1:n] ~ dlog.Y_1[1:n] + dlog.Y_2[1:n] +  dlog.Y_3[1:n] + dlog.Y_4[1:n] + dlog.Y_5[1:n] + dlog.X_1[1:n] + dlog.X_2[1:n] + dlog.X_3[1:n] + dlog.X_4[1:n] + dlog.X_5[1:n] + dlog.Z_1[1:n] + dlog.Z_2[1:n] + dlog.Z_3[1:n] + dlog.Z_4[1:n] + dlog.Z_5[1:n] + z);
  beta = adl.fit2$coef; 
  adl.d.hat2 = beta[1] + beta[2]*dlog.Y_0[n] + beta[3]*dlog.Y_1[n] + beta[4]*dlog.Y_2[n] + beta[5]*dlog.Y_3[n] + beta[6]*dlog.Y_4[n] + beta[7]*dlog.X_0[n] + beta[8]*dlog.X_1[n] + beta[9]*dlog.X_2[n] + beta[10]*dlog.X_3[n] + beta[11]*dlog.X_4[n] + beta[12]*dlog.Z_0[n] + beta[13]*dlog.Z_1[n] + beta[14]*dlog.Z_2[n] + beta[15]*dlog.Z_3[n] + beta[16]*dlog.Z_4[n] + beta[17] * z[n]; 
  adl.hat = log.Y[n] + adl.d.hat2; 
  e.adl.2[k] = log.Y[n+1] - adl.hat}

sd(e.adl.2)
```


```{r}
############### ADL_EC reduced 모형
z = lm(log.Y0[1:N]~log.X0[1:N]+log.Z0[1:N])$residual;
adl.ec.fit = lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] +  dlog.Y_3[1:N] + dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_1[1:N] + dlog.X_2[1:N] + dlog.X_3[1:N] + dlog.X_4[1:N] + dlog.X_5[1:N] + dlog.Z_1[1:N] + dlog.Z_2[1:N] + dlog.Z_3[1:N] + dlog.Z_4[1:N] + dlog.Z_5[1:N] + z)
summary(adl.ec.fit)

full.model.adl.ec <- adl.ec.fit
step.model.adl.ec <- stepAIC(full.model.adl.ec, direction='both', trace=F)
summary(step.model.adl.ec)
reduced.adl.ec <- lm(dlog.Y_0[1:N] ~ dlog.Y_1[1:N] + dlog.Y_2[1:N] + dlog.Y_3[1:N] + 
    dlog.Y_4[1:N] + dlog.Y_5[1:N] + dlog.X_3[1:N] + dlog.X_4[1:N] + 
      dlog.Z_1[1:N] + dlog.Z_2[1:N] + dlog.Z_3[1:N] + z)


e.adl.2.reduced = c()
for (k in 1:m) {
  n = N-k; 
  z = lm(log.Y0[1:n]~log.X0[1:n]+log.Z0[1:n])$residual;
  adl.fit2.ec = lm(dlog.Y_0[1:n] ~ dlog.Y_1[1:n] + dlog.Y_2[1:n] + dlog.Y_3[1:n] + 
    dlog.Y_4[1:n] + dlog.Y_5[1:n] + dlog.X_3[1:n] + dlog.X_4[1:n] + 
      dlog.Z_1[1:n] + dlog.Z_2[1:n] + dlog.Z_3[1:n] + z);
  beta = adl.fit2.ec$coef; 
  adl.d.hat2 = beta[1] + beta[2]*dlog.Y_0[n] + beta[3]*dlog.Y_1[n] + beta[4]*dlog.Y_2[n] + beta[5]*dlog.Y_3[n] + beta[6]*dlog.Y_4[n] + beta[7]*dlog.X_2[n] + beta[8]*dlog.X_3[n]
  + beta[9]*dlog.Z_0[n] + beta[10]*dlog.Z_1[n] + beta[11]*dlog.Z_2[n] + beta[12] * z[n]; 
  adl.hat = log.Y[n] + adl.d.hat2; 
  e.adl.2.reduced[k] = log.Y[n+1] - adl.hat}

sd(e.adl.2.reduced)
```


(4)
```{r}
############### VEC(2) 모형
library(tsDyn)

dataf = data.frame(y = log.demands, x = log.price, z = log.income)
bic = c()
for (p in 1:10){
  vecm.fit = VECM(dataf, lag = p, r = 1, estim = 'ML', include = 'const')
  bic[p] = summary(vecm.fit)$bic
}
which.min(bic)

vecm.fit = VECM(dataf, lag = 2, r = 1, estim = 'ML', include = 'const')


e.vec = c()
for (k in 1:m) {n = N-k; vecm.fit = VECM(dataf, lag = 2, r = 1, estim = 'ML', include = 'const'); vec.hat = predict(vecm.fit, n.ahead=1)[1]; e.vec[k] = log.demands[n+1] - vec.hat}
sd(e.vec)
```
