---
output: word_document
---

## 2.

```{r}
############# Riemann method #############
riemann <- function(ftn, a, b, n, threshold){
  
  # initial setting
  maxiter <- 1000
  err <- 1
  niter <- 1
  
  # initial value
  h <- (b-a)/n
  x <- seq(a, b, by = h)
  fx <- sapply(x, ftn)
  result <- h * sum(fx[1:n])
  
  while (err > threshold && niter <= maxiter){
    
    # save
    old_result <- result
    
    # update
    n <- n *2
    h <- (b-a)/n
    x <- seq(a, b, by = h)
    fx <- sapply(x, ftn)
    
    result <- h * sum(fx[1:n])
    
    # update error and niter
    err <- abs(result-old_result)
    niter <- niter + 1
    
  }
    
  return(c(result, niter, n, err))
}

############# Trapezoid method #############
trapezoid <- function(ftn, a, b, n, threshold) {
  
  # initial setting
  maxiter <- 1000
  err <- 1
  niter <- 1
  
  # initial value
  h <- (b-a)/n
  x <- seq(a, b, by = h)
  fx <- sapply(x, ftn)
  result <- h*(fx[1]/2 + sum(fx[2:n]) + fx[n+1]/2)
  
    
  while (err > threshold && niter <= maxiter){
    
    # save
    old_result <- result
    
    # update
    n <- n * 2
    h <- (b-a)/n
    x <- seq(a, b, by = h)
    fx <- ftn(x)
    
    result <- h*(fx[1]/2 + sum(fx[2:n]) + fx[n+1]/2)
    
    # update error and niter
    err <- abs(result-old_result)
    niter <- niter + 1
    
  }
  
  return(c(result, niter, n, err))
}

############# Simpson method #############
simpson <- function(ftn, a, b, n, threshold) {
  
  # initial setting
  maxiter <- 1000
  err <- 1
  niter <- 1
  
  # initial value
  n <- max(c(2*(n %/% 2), 4))
  h <- (b-a)/n
  x1 <- seq(a+h, b-h, by = 2*h)  # i가 홀수
  x2 <- seq(a+2*h, b-2*h, by = 2*h)  # i가 짝수
  fx1 <- sapply(x1, ftn)
  fx2 <- sapply(x2, ftn)
  result <- h/3*(ftn(a) + ftn(b) + 4*sum(fx1) + 2*sum(fx2))
  
  while (err > threshold && niter <= maxiter){
    
    # save
    old_result <- result
    
    # update
    n <- n * 2
    h <- (b-a)/n
    x1 <- seq(a+h, b-h, by = 2*h)  # i가 홀수
    x2 <- seq(a+2*h, b-2*h, by = 2*h)  # i가 짝수
    fx1 <- sapply(x1, ftn)
    fx2 <- sapply(x2, ftn)
    
    result <- h/3*(ftn(a) + ftn(b) + 4*sum(fx1) + 2*sum(fx2))
    
    # update error and niter
    err <- abs(result-old_result)
    niter <- niter + 1
    
    }
  
  return(c(result, niter, n, err))
}

############# R-integrate #############
## R에 내장된 integrate 함수 이용, 결과값으로 적분값, 구간개수, error 반환
inte <- function(ftn, a, b, threshold, n){
  result <- integrate(ftn, a, b, abs.tol = threshold, subdivisions = n)
  return(c(result$value, result$subdivisions, result$abs.error))
}
```

### 3개의 함수 예시
```{r}
# function 1
func1 <- function(x) (x-1)^3

inte(func1, 1, 3, 10^(-6), 2^(20))
system.time(inte(func1, 1, 3, 10^(-6), 2^(20)))
riemann(func1, 1, 3, 1, 10^(-6))
system.time(riemann(func1, 1, 3, 1, 10^(-6)))
trapezoid(func1, 1, 3, 1, 10^(-6))
system.time(trapezoid(func1, 1, 3, 1, 10^(-6)))
simpson(func1, 1, 3, 1, 10^(-6))
system.time(simpson(func1, 1, 3, 1, 10^(-6)))

# function 2
func2 <- function(x) log(x)/(1+x)

inte(func2, 1, 3, 10^(-6), 2^(20))
system.time(inte(func2, 1, 3, 10^(-6), 2^(20)))
riemann(func2, 1, 3, 1, 10^(-6))
system.time(riemann(func2, 1, 3, 1, 10^(-6)))
trapezoid(func2, 1, 3, 1, 10^(-6))
system.time(trapezoid(func2, 1, 3, 1, 10^(-6)))
simpson(func2, 1, 3, 1, 10^(-6))
system.time(simpson(func2, 1, 3, 1, 10^(-6)))


# function 3
func3 <- function(x) ((4*log(x^2)*x-sin(cos(x)))/(x^2+3*x))

inte(func3, 1, 3, 10^(-6), 2^(20))
system.time(inte(func3, 1, 3, 10^(-6), 2^(20)))
riemann(func3, 1, 3, 1, 10^(-6))
system.time(riemann(func3, 1, 3, 1, 10^(-6)))
trapezoid(func3, 1, 3, 1, 10^(-6))
system.time(trapezoid(func3, 1, 3, 1, 10^(-6)))
simpson(func3, 1, 3, 1, 10^(-6))
system.time(simpson(func3, 1, 3, 1, 10^(-6)))
```


## 3. (Problem 5.3)
###`a. 
```{r}
x <- c(6.52, 8.32, 0.31, 2.82, 9.96, 0.14, 9.64)

lik <- function(mu) dnorm(mu, mean(x), 3/sqrt(7))
prior <- function(mu) dcauchy(mu, 5, 2)
f <- function(mu) lik(mu)*prior(mu)

# R-integrate
int <- inte(f, -Inf, Inf, 10^(-10), 2^(20))
int
k <- 1/int[1]; k
system.time(inte(f, -Inf, Inf, 10^(-10), 2^(20)))

# Riemann
rie <- riemann(f, -10^(5), 10^(5), 1, 10^(-10))
rie
k <- 1/rie[1]; k
system.time(riemann(f, -10^(5), 10^(5), 1, 10^(-10)))

# Trapezoid 
tra <- trapezoid(f, -10^(5), 10^(5), 1, 10^(-10))
tra
k <- 1/tra[1]; k
system.time(trapezoid(f, -10^(5), 10^(5), 1, 10^(-10)))

# Simpson
sim <- simpson(f, -10^(5), 10^(5), 1, 10^(-10))
sim
k <- 1/sim[1]; k
system.time(simpson(f, -10^(5), 10^(5), 1, 10^(-10)))
```

### b. 
```{r}
k<- 7.84654
post <- function(mu) k * f(mu)

int <- inte(post, 2, 8, 0.0001, 2^(20))
int
system.time(inte(post, 2, 8, 0.0001, 2^(20)))

# Riemann
rie <- riemann(post, 2, 8, 1, 0.0001)
rie
system.time(riemann(post, 2, 8, 1, 0.0001))

# Trapezoid 
tra <- trapezoid(post, 2, 8, 1, 0.0001)
tra
system.time(trapezoid(post, 2, 8, 1, 0.0001))

# Simpson
sim <- simpson(post, 2, 8, 1, 0.0001)
sim
system.time(simpson(post, 2, 8, 1, 0.0001))
```


### c.
```{r}
## u <- exp(mu)/(1+exp(mu))
## mu <- log(u/(1-u))
## dmu <- du * 1/(u*(1-u))

trans_post <- function(u) post(log(u / (1 - u))) / u / (1 - u)

a1 <- exp(3) / (1 + exp(3))
b1 <- 1- 1e-10

inte(trans_post, a1, b1, 10^(-8), 2^(20))
system.time(inte(trans_post, a1, b1, 10^(-8), 2^(20)))
riemann(trans_post, a1, b1, 1, 10^(-8))
system.time(riemann(trans_post, a1, b1, 1, 10^(-8)))
trapezoid(trans_post, a1, b1, 1, 10^(-8))
system.time(trapezoid(trans_post, a1, b1, 1, 10^(-8)))
simpson(trans_post, a1, b1, 1, 10^(-8))
system.time(simpson(trans_post, a1, b1, 1, 10^(-8)))


## transformation 필요
## v <- asin(u)
## u <- sin(v)
## du <- cos(v)

trans_post_2 <- function(v) post(log(sin(v)/(1-sin(v))))/sin(v)/(1-sin(v)) * cos(v)

a2 <- asin(a1)
b2 <- asin(1)

inte(trans_post_2, a2, b2, 10^(-8), 2^(20))
system.time(inte(trans_post_2, a2, b2, 10^(-8), 2^(20)))
riemann(trans_post_2, a2, b2, 1, 10^(-8))
system.time(riemann(trans_post_2, a2, b2, 1, 10^(-8)))
```

### d.
```{r}
## u <- 1/mu
## mu <- 1/u
## dmu <- du * (1/u^2)

trans_post_3 <- function(u) post(1/u) * (1/u)^2
  
a11 <- 1e-10
b11 <- 1/3
  
inte(trans_post_3, a11, b11, 10^(-7), 2^(20))
system.time(inte(trans_post_3, a11, b11, 10^(-7), 2^(20)))
riemann(trans_post_3, a11, b11, 1, 10^(-7))
system.time(riemann(trans_post_3, a11, b11, 1, 10^(-7)))
trapezoid(trans_post_3, a11, b11, 1, 10^(-7))
system.time(trapezoid(trans_post_3, a11, b11, 1, 10^(-7)))
simpson(trans_post_3, a11, b11, 1, 10^(-7))
system.time(simpson(trans_post_3, a11, b11, 1, 10^(-7)))


## v <- acos(u)
## u <- cos(v)
## du <- dv *-sin(v)

trans_post_4 <-  function(v) post(1/cos(v)) * (1/cos(v))^2 * -sin(v)

a12 <-  acos(0)
b12 <- acos(b11)

inte(trans_post_4, a12, b12, 10^(-7), 2^(20))
system.time(inte(trans_post_4, a12, b12, 10^(-7), 2^(20)))
riemann(trans_post_4, a12, b12, 1, 10^(-7))
system.time(riemann(trans_post_4, a12, b12, 1, 10^(-7)))
trapezoid(trans_post_4, a12, b12, 1, 10^(-7))
system.time(trapezoid(trans_post_4, a12, b12, 1, 10^(-7)))
simpson(trans_post_4, a12, b12, 1, 10^(-7))
system.time(simpson(trans_post_4, a12, b12, 1, 10^(-7)))
```


## 4 (Problem 5.4)

```{r}
trap <- function(ftn, a, b, n) {
  h <- (b-a)/n
  x <- seq(a, b, by = h)
  fx <- sapply(x, ftn)
  h*(fx[1]/2 + sum(fx[2:n]) + fx[n+1]/2)
}

romberg <- function(ftn, a, b, n, m){
  
  h <- (b-a)/n
  x <- seq(a, b, by = h)
  fx <- sapply(x, ftn)
  R <- matrix(0, nrow=7, ncol = 7)
  
  R[1,1] <- h*(fx[1]/2 + fx[2]/2)
  
  for (i in 1:m){
    R[i+1, 1] = trap(ftn, a, b, n=2^i)
    for (j in 1:i){
      R[i+1, j+1] = (4^(j) * R[(i+1), j] - R[i, j]) / (4^(j)-1)
    }
  }
  return(R)
}

func4 <- function(x) 1/x

romberg(func4, 1, 5, 1, m=6)
system.time(romberg(func4, 1, 5, 1, m=6))
romberg(func4, 1, 10, 1, m=6)
system.time(romberg(func4, 1, 10, 1, m=6))
```




